version: "3.9"
services:
  exchange_parser:
    container_name: exchange_parser
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - exchange-network
    depends_on:
      postgres-service:
        condition: service_healthy
      redis-service:
        condition: service_healthy
    volumes:
      - ./:/exchange_parser

  postgres-service:
    image: postgres:17.0-bookworm
    container_name: postgres_container
    env_file:
      - .env
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGHOST: ${POSTGRES_HOST}
      PGPORT: ${POSTGRES_PORT}
      PGDATABASE: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/expense_accounting/postgresql/exchange_parser
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - exchange-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-service:
    image: redis:alpine
    container_name: redis_container
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - exchange-network
volumes:
  postgres_data:

networks:
  exchange-network:
    driver: bridge